# 
# ps8pr3.py - Problem Set 8, Problem 3
#
# Markov Text
#


# Problem 1 

import random 

def create_dictionary(filename):
    """ takes a string representing the name of a text file, and that returns 
    a dictionary of key-value pairs
    """
    file = open(filename, 'r')
    text = file.read()      
    file.close()
    words = text.split()
    d = {}
    current_word = '$'
    for next_word in words:
        if current_word not in d:
            d[current_word] = [next_word]
        else:
            d[current_word] += [next_word]
        if next_word[-1] in '.?!':
            current_word = '$'
        else:
            current_word = next_word
    return d 

def generate_text(word_dict, num_words):
    """
     that takes as parameters a dictionary of word transitions (generated by 
     the create_dictionary function) named word_dict and a positive integer 
     named num_words
    """
    current_word = '$' 
    
    for i in range(0, num_words):
        if current_word[-1] in '!.?':
            current_word = '$'
        else:
            wordlist = word_dict[current_word]
            next_word = random.choice(wordlist)
            current_word = next_word 
            print(current_word, end=' ')
    print('.')
        